apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: logging
spec:
  version: 8.5.1
  secureSettings: []
  http:
    tls:
      selfSignedCertificate:
        disabled: true  # Отключаем SSL
  nodeSets:
    - name: default
      count: 1
      config:
        xpack.security.enabled: true
        xpack.security.transport.ssl.enabled: false
        xpack.security.http.ssl.enabled: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
