apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cluster
  namespace: elastic-system
spec:
  version: 8.5.1
  nodeSets:
    - name: default
      count: 2
      config:
        cluster.name: "elasticsearch"
        node.roles: ["master", "data", "ingest"]
        discovery.seed_hosts: ["elasticsearch-master-0", "elasticsearch-master-1"]
        xpack.security.enabled: true
        xpack.security.authc.realms.oidc.oidc1.enabled: true
        xpack.security.authc.realms.oidc.oidc1.rp.client_id: "kibana"
        xpack.security.authc.realms.oidc.oidc1.rp.redirect_uri: "https://kibana.msv-tech.ru/oauth2/callback"
        xpack.security.authc.realms.oidc.oidc1.rp.post_logout_redirect_uri: "https://msv-tech.ru/"
        xpack.security.authc.realms.oidc.oidc1.rp.requested_scopes: ["openid", "profile", "email"]
        xpack.security.authc.realms.oidc.oidc1.rp.response_type: "code"

      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi


# kubectl apply -f elasticsearch-value.yaml