apiVersion: v1
kind: Secret
metadata:
  name: oidc-client-secret
  namespace: logging
type: Opaque
stringData:
  xpack.security.authc.realms.oidc.oidc1.rp.client_secret: "MCbDEJvVwr2gHf669ah2i5vr7fCIgQ4z"
