apiVersion: stackconfigpolicy.k8s.elastic.co/v1alpha1
kind: StackConfigPolicy
metadata:
  name: test-stack-config-policy
spec:
  resourceSelector:
    matchLabels:
      env: my-label
  elasticsearch:
    secureSettings:
      - secretName: oidc-client-secret
    securityRoleMappings:
      oidc_kibana:
        roles: [ "superuser" ]
        rules:
          all:
            - field: { realm.name: "oidc1" }
            - field: { username: "<username>" }
        enabled: true
    config:
      logger.org.elasticsearch.discovery: DEBUG
      xpack:
        security:
          authc:
            token.enabled: true
            realms:
              oidc:
                oidc1:
                  order: 2
                  rp.client_id: "<client id>"
                  rp.response_type: "code"
                  rp.requested_scopes: ["openid", "email"]
                  rp.redirect_uri: "${KIBANA_URL}/api/security/oidc/callback"
                  op.issuer: "https://accounts.google.com"
                  op.authorization_endpoint: "https://accounts.google.com/o/oauth2/v2/auth"
                  op.token_endpoint: "https://oauth2.googleapis.com/token"
                  op.userinfo_endpoint: "https://openidconnect.googleapis.com/v1/userinfo"
                  op.jwkset_path: "https://www.googleapis.com/oauth2/v3/certs"
                  claims.principal: email
                  claim_patterns.principal: "^([^@]+)@elastic\\.co$"
  kibana:
    config:
      xpack.security.authc.providers:
        oidc.oidc1:
          order: 0
          realm: oidc1
          description: "Log in with GCP"
        basic.basic1:
          order: 1