apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat
  namespace: logging
spec:
  type: metricbeat
  version: 8.5.1
  elasticsearchRef:
    name: elastic
  kibanaRef:
    name: kibana
  config:
    metricbeat.modules:
      - module: prometheus
        period: 15s
        hosts: ["http://kube-state-metrics.kube-system.svc.cluster.local:8080"]
        metrics_path: "/metrics"
        query:
          help: kube_.*
        fields:
          service: kube-state-metrics
      - module: system
        metricsets:
          - cpu
          - memory
          - network
          - filesystem
          - process
          - process_summary
        period: 10s
        processes: [ '.*' ]
        cpu.metrics: [ "percentages", "normalized_percentages" ]
      - module: kubernetes
        metricsets:
          - node
          - pod
          - container
          - volume
        period: 10s
        hosts: [ "https://${NODE_NAME}:10250" ]
        ssl.verification_mode: none
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes.ssl.certificate_authorities:
          - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    setup.ilm.enabled: false
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: metricbeat-sa
        containers:
          - name: metricbeat
            image: docker.elastic.co/beats/metricbeat:8.5.1
            args: ["-e", "-c", "/etc/beat.yml"]
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: config
                mountPath: /etc/beat.yml
                subPath: beat.yml
              - name: elasticsearch-certs
                mountPath: /mnt/elastic-internal/elasticsearch-certs
                readOnly: true
              - name: kibana-certs
                mountPath: /mnt/elastic-internal/kibana-certs
                readOnly: true
              - name: beat-data
                mountPath: /usr/share/metricbeat/data
        volumes:
          - name: config
            secret:
              secretName: metricbeat-beat-metricbeat-config
          - name: elasticsearch-certs
            secret:
              secretName: metricbeat-beat-es-ca
          - name: kibana-certs
            secret:
              secretName: metricbeat-beat-kibana-ca
          - name: beat-data
            hostPath:
              path: /var/lib/logging/metricbeat/metricbeat-data
              type: DirectoryOrCreate
