apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - pods
      - services
      - endpoints
      - secrets
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: metricbeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: metricbeat-sa
    namespace: logging
