name: authservice
namespace: monitoring
namespaceMonitoring: default
replicas: 1

image:
  repository: maxim58r/authservice
  tag: 1.0.0

containerPort: 8080
nodePort: 31000

springProfilesActive: "ift"
release: prom-stack
server:
  port: 8080
