apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: msv-tech-tls
  namespace: keycloak
spec:
  secretName: msv-tech-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - msv-tech.ru
    - keycloak.msv-tech.ru
    - kibana.msv-tech.ru

# kubectl apply -f certificate.yaml
# kubectl get certificate -n keycloak