installCRDs: true
logLevel: 2
replicaCount: 1
leaderElection:
  namespace: kube-system

controller:
  image:
    registry: docker.io
    repository: bitnami/cert-manager
    tag: 1.17.1-debian-12-r2
    pullPolicy: IfNotPresent
  resourcesPreset: "nano"
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
  serviceAccount:
    create: true

webhook:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/cert-manager-webhook
    tag: 1.17.1-debian-12-r2
    pullPolicy: IfNotPresent
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true

cainjector:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/cainjector
    tag: 1.17.1-debian-12-r2
    pullPolicy: IfNotPresent
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: false
