# Количество реплик (два узла в кластере)
replicas: 2

# Минимальное количество master-нод для кворума
minimumMasterNodes: 2  # (master_eligible_nodes / 2) + 1 → (2 / 2) + 1 = 2

# Роли для узлов
roles:
  - master
  - data
  - ingest

# Включаем безопасность, но TLS отключаем
security:
  enabled: true  # Оставляем security включённым для OIDC
  tls:
    enabled: false  # Отключаем TLS

# Keystore для OIDC client_secret
keystore:
  - secretName: oidc-client-secret
    items:
      - key: client-secret
        path: xpack.security.authc.realms.oidc.oidc1.rp.client_secret

# Основная конфигурация Elasticsearch
esConfig:
  elasticsearch.yml: |
    cluster.name: "elasticsearch"
    node.name: ${HOSTNAME}

    # Убираем single-node и делаем полноценный кластер
    discovery.seed_hosts: ["elasticsearch-master-0", "elasticsearch-master-1"]
    cluster.initial_master_nodes: ["elasticsearch-master-0", "elasticsearch-master-1"]

    # Роли ноды
    node.roles: ["master", "data", "ingest"]

    # Включаем безопасность (OIDC требует xpack.security.enabled=true)
    xpack.security.enabled: true
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

    # OIDC конфигурация
    xpack.security.authc.realms.oidc.oidc1.enabled: true
    xpack.security.authc.realms.oidc.oidc1.order: 10
    xpack.security.authc.realms.oidc.oidc1.rp.client_id: "myKeycloakClientId"
    xpack.security.authc.realms.oidc.oidc1.rp.response_type: "code"
    xpack.security.authc.realms.oidc.oidc1.rp.redirect_uri: "https://elasticsearch.chatter.com/api/security/v1/oidc"
    xpack.security.authc.realms.oidc.oidc1.rp.post_logout_redirect_uri: "https://elasticsearch.chatter.com/"
    xpack.security.authc.realms.oidc.oidc1.op.authorization_endpoint: "https://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/auth"
    xpack.security.authc.realms.oidc.oidc1.op.issuer: "https://192.168.1.35:32080/realms/Chatter"
    xpack.security.authc.realms.oidc.oidc1.op.jwkset_path: "https://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/certs"
    xpack.security.authc.realms.oidc.oidc1.op.token_endpoint: "https://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/token"
    xpack.security.authc.realms.oidc.oidc1.claims.principal: sub

# Переменные окружения
extraEnvs:
  - name: ELASTIC_PASSWORD
    value: "QJaWS1Bi7ULkaWfJc*Hi"

# Хранилище для данных Elasticsearch
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi  # Увеличил с 1Gi, так как кластерная работа требует больше места

# Ресурсы для каждого пода
resources:
  requests:
    cpu: "1"
    memory: "2Gi"  # Увеличил память до 2ГБ, чтобы кластер работал стабильнее
  limits:
    cpu: "2"
    memory: "2Gi"
