# Количество реплик и прочие базовые настройки
replicas: 2
minimumMasterNodes: 2
antiAffinity: "soft"
roles:
  - master
  - data
  - ingest

# Включаем security и HTTP TLS
security:
  enabled: true
  tls:
    enabled: true

# Keystore для OIDC (пример)
keystore:
  - secretName: oidc-client-secret
    items:
      - key: client-secret
        path: xpack.security.authc.realms.oidc.oidc1.rp.client_secret

# Основная конфигурация Elasticsearch
esConfig:
  elasticsearch.yml: |
    cluster.name: "elasticsearch"
    node.name: ${HOSTNAME}
    node.roles: ["master", "data", "ingest"]
    
    discovery.seed_hosts: ["elasticsearch-master-0", "elasticsearch-master-1"]
    cluster.initial_master_nodes: ["elasticsearch-master-0", "elasticsearch-master-1"]

    xpack.security.enabled: true

    ####################################################
    # TRANSPORT SSL (порт 9300)
    ####################################################
    xpack.security.transport.ssl.enabled: true
    
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/tls.key
    xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/tls.crt
    xpack.security.transport.ssl.certificate_authorities: [ "/usr/share/elasticsearch/config/certs/ca.crt" ]

    ####################################################
    # HTTP SSL (порт 9200) HTTPS
    ####################################################
    xpack.security.http.ssl.enabled: true
    
    xpack.security.http.ssl.verification_mode: certificate
    xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/tls.key
    xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/tls.crt
    xpack.security.http.ssl.certificate_authorities: [ "/usr/share/elasticsearch/config/certs/ca.crt" ]

    ####################################################
    # ODIC
    ####################################################
    xpack.security.authc.realms.oidc.oidc1.enabled: true
    xpack.security.authc.realms.oidc.oidc1.order: 10
    xpack.security.authc.realms.oidc.oidc1.rp.client_id: "myKeycloakClientId"
    xpack.security.authc.realms.oidc.oidc1.rp.response_type: "code"
    xpack.security.authc.realms.oidc.oidc1.rp.redirect_uri: "https://elasticsearch.chatter.com/api/security/v1/oidc"
    xpack.security.authc.realms.oidc.oidc1.rp.post_logout_redirect_uri: "https://elasticsearch.chatter.com/"
    xpack.security.authc.realms.oidc.oidc1.op.authorization_endpoint: "https://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/auth"
    xpack.security.authc.realms.oidc.oidc1.op.issuer: "https://192.168.1.35:32080/realms/Chatter"
    xpack.security.authc.realms.oidc.oidc1.op.jwkset_path: "https://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/certs"
    xpack.security.authc.realms.oidc.oidc1.op.token_endpoint: "https://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/token"
    xpack.security.authc.realms.oidc.oidc1.claims.principal: sub

# Пароль суперпользователя elastic
extraEnvs:
  - name: ELASTIC_PASSWORD
    value: "QJaWS1Bi7ULkaWfJc*Hi"

# PVC для данных
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

# Ресурсы
resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"