ingress:
  enabled: true  # Включаем Ingress для Keycloak
  ingressClassName: "nginx"  # Используем Nginx Ingress
  pathType: Prefix
  apiVersion: "networking.k8s.io/v1"
  controller: default
  hostname: keycloak.local
  hostnameStrict: false
  path: "/"
  servicePort: https  # Используем HTTPS
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt  # Настраиваем Let's Encrypt для автоматического получения сертификатов
  tls: true  # Включаем TLS для HTTPS
  selfSigned: false
  extraTls:
    - hosts:
        - keycloak.local
      secretName: keycloak-tls  # Имя секрета для сертификата
