# kibana-values.yaml

# Настройка безопасности Kibana
xpack:
  security:
    enabled: true

# Настройка аутентификации OIDC
elasticsearch:
  hosts:
    - "http://elasticsearch-master:9200"

server:
  host: "0.0.0.0"
  port: 5601

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
    - host: your-kibana-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kibana-tls
      hosts:
        - your-kibana-domain.com

# Настройка OIDC
oidc:
  enabled: true
  realm: "oidc1" # Должно совпадать с названием реалма в Elasticsearch
  client_id: "myKeycloakClientId" # ID клиента в Keycloak
  client_secret: "${xpack.security.authc.realms.oidc.oidc1.rp.client_secret}" # Ссылка на секрет
  redirect_uri: "http://your-kibana-domain.com/api/security/v1/oidc"
  post_logout_redirect_uri: "http://your-kibana-domain.com/"
  issuer: "http://192.168.1.35:32080/realms/Chatter" # URL вашего Keycloak реалма

# Ресурсы и масштабирование
resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

replicas: 1