replicaCount: 1

##########################################################
# Подключаемся к ES по HTTPS
##########################################################
elasticsearchHosts: "https://elasticsearch-master:9200"

elasticsearch:
  username: "elastic"
  password: "QJaWS1Bi7ULkaWfJc*Hi"

service:
  type: NodePort
  port: 5601
  nodePort: 30081  # наружный порт, если нужно внешнее подключение

##########################################################
# Конфигурация kibana.yml
##########################################################
kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "https://kibana.chatter.com"

    elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
    elasticsearch.ssl.verificationMode: certificate

    xpack.security.authc.providers:
      basic.basic1:
        order: 0
      oidc.oidc1:
        order: 1
        realm: "oidc1"

    xpack.security.authc.oidc.oidc1:
      order: 1
      realm: "oidc1"
      authorization_endpoint: "https://keycloak.chatter.com/realms/Chatter/protocol/openid-connect/auth"
      token_endpoint: "https://keycloak.chatter.com/realms/Chatter/protocol/openid-connect/token"
      userinfo_endpoint: "https://keycloak.chatter.com/realms/Chatter/protocol/openid-connect/userinfo"
      jwkset_path: "https://keycloak.chatter.com/realms/Chatter/protocol/openid-connect/certs"
      client_id: "kibana-client"
      client_secret: "sAcCHLav7Q891svS8SmE27KLFNL2hwvr"
      redirect_uri: "https://kibana.chatter.com/api/security/v1/oidc"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"

########################################################################
# Включаем pre-install Token Creation (по умолчанию включён),
# и разрешаем чарту сам монтировать CA (или сделаем вручную).
########################################################################
preInstallTokenCreation:
  enabled: false
  automountElasticsearchCerts: true
