# kibana-oidc.yaml

replicaCount: 1

# Указываем адрес Elasticsearch по HTTP внутри кластера:
elasticsearchHosts: "http://elasticsearch-master:9200"

# Логин/пароль
elasticsearch:
  username: "elastic"
  password: "QJaWS1Bi7ULkaWfJc*Hi"

service:
  type: NodePort
  port: 5601
  nodePort: 30081

# Снимаем SSL-настройки и отключаем автоматический монтаж сертификатов
preInstallTokenCreation:
  automountElasticsearchCerts: false
  # Параметр enabled: true по умолчанию, пусть будет true
  # Токен всё равно будет пытаться создаваться, но уже без лишнего SSL

# Или вообще можно отключить pre-install Job, если ты не пользуешься security token в Kibana:
# preInstallTokenCreation:
#   enabled: false

# Отключим проверку TLS на случай, если где-то внезапно включен https
kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "http://192.168.1.35:30081"
    elasticsearch.ssl.verificationMode: none

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
