replicaCount: 1

##########################################################
# Подключаемся к ES по HTTPS
##########################################################
elasticsearchHosts: "https://elasticsearch-master:9200"

elasticsearch:
  username: "elastic"
  password: "QJaWS1Bi7ULkaWfJc*Hi"

service:
  type: NodePort
  port: 5601
  nodePort: 30081  # наружный порт, если нужно внешнее подключение

##########################################################
# Конфигурация kibana.yml
##########################################################
kibanaConfig:
  kibana.yml: |
    # Если хотите открыть Kibana наружу
    server.publicBaseUrl: "https://192.168.1.35:30081"
    
    # Указываем CA, чтобы Kibana доверяла сертификату ES
    elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
    
    # Проверяем сертификат (можно заменить на "full" для более строгой проверки)
    elasticsearch.ssl.verificationMode: certificate
    
    # Настройка OIDC
    xpack.security.authc:
      providers:
        basic.basic1:
          order: 0
        oidc.oidc1:
          order: 1
          realm: "oidc1"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"

########################################################################
# Включаем pre-install Token Creation (по умолчанию включён),
# и разрешаем чарту сам монтировать CA (или сделаем вручную).
########################################################################
preInstallTokenCreation:
  enabled: false
  automountElasticsearchCerts: true
