# kibana-oidc.yaml

replicaCount: 1

# Подключение к Elasticsearch внутри кластера (HTTP, без TLS)
elasticsearchHosts: "http://elasticsearch-master:9200"

# Убедись, что такой пользователь есть.
# Или просто используем "elastic" — его точно знаем.
elasticsearch:
  username: "elastic"
  password: "QJaWS1Bi7ULkaWfJc*Hi"

service:
  type: NodePort
  port: 5601
  nodePort: 30081  # Kibana будет доступна извне на http://192.168.1.35:30081

# Дополнительные переменные окружения (дублирует логин/пароль elastic):
extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "QJaWS1Bi7ULkaWfJc*Hi"

# Дополнительная конфигурация Kibana
kibanaConfig:
  kibana.yml: |
    # Адрес Kibana извне
    server.publicBaseUrl: "http://192.168.1.35:30081"

    # Если нет HTTPS на Elasticsearch, нет смысла проверять сертификат
    # (Но это строка не повредит, если где-то включится TLS)
    elasticsearch.ssl.verificationMode: none

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
