# Количество реплик Kibana
replicaCount: 1

# Тип сервиса: NodePort, чтобы был доступен извне
service:
  type: NodePort
  port: 5601
  nodePort: 30081  # Выберите свободный порт из диапазона 30000-32767

# Подключение к Elasticsearch
# Укажем URL вашего Elasticsearch + базовую авторизацию
elasticsearchHosts: ["https://192.168.1.35:30080"]  # NodePort вашего Elasticsearch
# Если хотите указывать внутри кластера, можете взять Service (https://elasticsearch-master.logging.svc:9200)
# Но тогда Kibana будет работать только внутри кластера, либо придётся раздавать Kibana наружу.

extraEnvs:
  # Логин/пароль пользователя elastic (тот же что у ES)
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "QJaWS1Bi7ULkaWfJc*Hi"

# Отключим проверку сертификата, если у вас самоподписанный
kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "http://192.168.1.35:30081"
    elasticsearch.ssl.verificationMode: none

# Ресурсы (минимальные)
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
