elasticsearch:
  hosts:
    - "https://elasticsearch-master.logging.svc.cluster.local:9200" # Используем HTTPS
  username: "elastic"
  passwordFromSecret:
    name: elasticsearch-master-credentials
    key: password
  ssl:
    verificationMode: "none" # Можно заменить на "full" при наличии CA

kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "http://192.168.1.35:31864"
    xpack.security.enabled: true
    xpack.security.authc.providers:
      oidc.oidc1:
        order: 0
        realm: "oidc1"
    xpack.security.authc.oidc.realm: "oidc1"

    # Указываем секретный ключ OIDC
    xpack.security.authc.realms.oidc.oidc1:
      rp.client_id: "myKeycloakClientId"
      rp.client_secret: "${xpack.security.authc.realms.oidc.oidc1.rp.client_secret}" # Используем секрет
      rp.redirect_uri: "http://192.168.1.35:31864/api/security/v1/oidc"
      rp.post_logout_redirect_uri: "http://192.168.1.35:31864/"
      op.issuer: "http://192.168.1.35:32080/realms/Chatter"

ingress:
  enabled: false # Выключаем Ingress, так как Kibana работает через NodePort

service:
  type: NodePort
  nodePorts:
    http: 31864

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi
