apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}-monitor
  namespace: {{ .Values.namespace }}        # может быть default или другой namespace, но чаще всего monitoring
  labels:
    app: {{ .Values.name }}
    release: {{ .Values.release }}          # очень важно для селектора Prometheus Operator
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}               # совпадает с лейблом сервиса
  namespaceSelector:
    matchNames:
      - {{ .Values.namespaceMonitoring }}   # если service в default
  endpoints:
    - port: http                            # имя должно совпадать с service.spec.ports[]
      path: /actuator/prometheus
      interval: 30s
