apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authservice-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: authservice
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
