# Для kibana_system
apiVersion: v1
kind: Secret
metadata:
  name: kibana-token-secret
  namespace: logging
type: Opaque
data:
  password: 'HJpZsxOvmLIZm6ih+V-m'

---

# Для elastic
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-password
  namespace: logging
type: Opaque
data:
  elasticsearch-password: 'HJpZsxOvmLIZm6ih+V-m'

---

# Для keycloak
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  admin-password: 'rq6jL.!gTdi?n#L1'
  postgresql-password: 'rq6jL.!gTdi?n#L1'

