apiVersion: v1
kind: Namespace
metadata:
  name: redis

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: redis
type: Opaque
stringData:
  redis-password: "CfAb11y5gLQ3quvc"

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-shared
  namespace: redis
spec:
  releaseName: redis-shared
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
      version: "*"
  interval: 1m
  values:
    auth:
      enabled: true
      existingSecret: redis-password
      existingSecretPasswordKey: redis-password
    replica:
      replicaCount: 0
    persistence:
      enabled: true
      storageClass: local-path
    service:
      type: LoadBalancer
