apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis-shared
  namespace: redis
spec:
  auth:
    enabled: true
    existingSecret: redis-shared-auth
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.11
    imagePullPolicy: IfNotPresent
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.0.4  # обязательное поле даже если disabled
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
