apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    server:
      port: {{ .Values.server.port }}
    spring:
      application:
        name: {{ .Values.name }}
        redis:
          enabled: false
    management:
      endpoints:
        web:
          exposure:
            include: "*"
        base-path: /actuator
      endpoint:
        health:
          probes:
            enabled: true
          show-details: ALWAYS
