name: authservice
namespace: default
replicas: 1

image:
  repository: maxim58r/authservice
  tag: 1.0.0

containerPort: 8080
nodePort: 31000

server:
  port: 8080

springProfilesActive: "ift"

datasource:
  host: 192.168.1.35
  port: 32172
  dbName: postgres_auth
  password: ""  # в реальном проекте храним в Secret

spring:
  application:
    name: authservice
  datasource:
    username: postgres
    url: ""  # пусто, потому что собираем в шаблоне
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddlAuto: validate
    showSql: true
    properties:
      hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
  management:
    endpoint:
      health:
        probes:
          enabled: true

redis:
  host: 192.168.1.35
  port: 31015
  connectTimeout: 60000
  passwordFromSecret: ""

jwt:
  secret: secret_key
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        boot:
          context:
            properties: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

deployment:
  annotations:
    redeploy: ""

liveness:
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 40
  periodSeconds: 5

readiness:
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 40
  periodSeconds: 5

globalConfigMap: global-configmap
serviceAccountName: authservice-sa

storage:
  size: 100Mi
