name: authservice
namespace: default
replicas: 1

image:
  repository: maxim58r/authservice
  tag: 1.0.0

containerPort: 8080

server:
  port: 8080

springProfilesActive: "ift"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3


globalConfigMap: global-configmap

serviceAccountName: authservice-sa

storage:
  size: 100Mi

spring:
  application:
    name: authservice

  datasource:
    url: jdbc:postgresql://{{ .Values.datasource.host }}:{{ .Values.datasource.port }}/postgres_auth
    username: postgres
    password: "{{ .Values.datasource.password }}" # Перенесите в секреты
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddlAuto: validate
    showSql: true
    properties:
      hibernateDialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin

redis:
  host: 192.168.1.35
  port: 31015
  connectTimeout: 60000
  passwordFromSecret: redis-password

jwt:
  secret: secret_key
  expiration: 3600000 # 1 час

logging:
  level:
    org.springframework.boot.context.properties: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

datasource:
  host: 192.168.1.35
  port: 32172
  password: postgres # Перенесите в секреты

secrets:
  redisPassword: "CfAb11y5gLQ3quvc"
  datasourcePassword: "postgres"
