name: apigatewaysservice
replicas: 2

image:
  repository: maxim58r/apigatewayservice
  tag: 1.0.0

containerPort: 8080

springProfilesActive: "prod"

liveness:
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5

readiness:
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
