apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.5.1
  count: 1
  config:
    elasticsearch.hosts:
      - "https://elastic-es-http.logging.svc:9200"
    elasticsearch.username: "adminuser"            # Имя пользователя для подключения Kibana к Elasticsearch
    elasticsearch.ssl.verificationMode: "full"     # Включаем полную проверку сертификата Elasticsearch
    elasticsearch.ssl.certificateAuthorities:
      - "/usr/share/kibana/config/certs/tls.crt"   # Подключаем сертификат CA Elasticsearch (самоподписанный)
  secureSettings:
    - secretName: kibana-elasticsearch-credentials # Secret с паролем для подключения к Elasticsearch
  podTemplate:
    spec:
      containers:
        - name: kibana
          volumeMounts:
            - name: elasticsearch-ca
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
      volumes:
        - name: elasticsearch-ca
          secret:
            secretName: elastic-es-http-certs-public
