replicaCount: 1

##########################################################
# Подключаемся к ES по HTTPS
##########################################################
elasticsearch:
  hosts:
    - "https://elasticsearch-master"
  port: 9200
  security:
    auth:
      existingSecret: "kibana-token-secret"
      passwordSecretKey: password

logging.verbose: true

service:
  type: NodePort
  port: 5601
  nodePort: 30081  # наружный порт, если нужно внешнее подключение

##########################################################
# Конфигурация kibana.yml
##########################################################
kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: "https://msv-tech.ru"
    elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
    elasticsearch.ssl.verificationMode: full

    xpack.security.authc.providers:
      oidc.oidc1:
        order: 0
        realm: "oidc1"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"
