apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.5.1
  count: 1
  elasticsearchRef:
    name: elastic
  secureSettings:
    - secretName: kibana-oidc-secure-settings
  config:
    elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
    elasticsearch.hosts: ["https://elastic-es-http.logging.svc:9200"]
    elasticsearch.ssl.verificationMode: full
    xpack.reporting.kibanaServer.hostname: localhost
    server.ssl.enabled: true
    elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/es-certs/ca.crt"]
    server.ssl.certificate: /usr/share/kibana/config/kibana-certs/tls.crt
    server.ssl.key: /usr/share/kibana/config/kibana-certs/tls.key


  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-es-elastic-user
                  key: elastic
          volumeMounts:
            - name: es-ca
              mountPath: /usr/share/kibana/config/es-certs
            - name: kibana-cert
              mountPath: /usr/share/kibana/config/kibana-certs
      volumes:
        - name: es-ca
          secret:
            secretName: elastic-tls-secret
        - name: kibana-cert
          secret:
            secretName: kibana-msv-tech-tls
