apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.5.1
  count: 1
  config:
    elasticsearch.hosts:
      - "https://elastic-es-http.logging.svc:9200"
    elasticsearch.serviceAccountToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjJoZExxbV9MUmkzejFWYkVTQ0E1cFFjVUw2R3o1U2tDQWdfdXNuZGtPQ2cifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzQyMjM5NjMwLCJpYXQiOjE3NDIyMzYwMzAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiY2MzMjg3MDktYjlhNy00N2ZmLWJhMTMtMzdhNDQ0YmYzMTJlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJsb2dnaW5nIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImtpYmFuYS1zYSIsInVpZCI6ImZkOTBjNWFhLTY3YjQtNDdkOC1hNjdlLTg0NWQ3YjFiOTM0MyJ9fSwibmJmIjoxNzQyMjM2MDMwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bG9nZ2luZzpraWJhbmEtc2EifQ.LG4oNfdRpXpGljExvr4yIa-8sDHrvJ-ilfjsEqEY_0L5E8fv_yAek6k8pIPWylULv4MwOQnK81UlHk2i6Ox3m8doN_jWNjOwbDQTYl7TJhhP57zLfQYunCs6tZbTJfiEhleQmsCJYOJv9qvbOUVa403zr7ImcKeVv9w7AaL3KL1NrDHcyO2UfxAexSvbJ8ApvZGGoMde03oT51kI2bulguCEWmBq4NFPxNBGn930D-heMO3sId_h_cNofgkbAnkRVCZDGd9nML7ra4enH2pgReDqQ2dYBcQP7MpF0zpOzg9vFfrEc576zVALpahdtqzy4Jl7KVyKCZrUDIBOTUwhGA"
    elasticsearch.ssl.verificationMode: "full"
    elasticsearch.ssl.certificateAuthorities:
      - "/usr/share/kibana/config/certs/tls.crt"
  podTemplate:
    spec:
      containers:
        - name: kibana
          volumeMounts:
            - name: elasticsearch-ca
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
      volumes:
        - name: elasticsearch-ca
          secret:
            secretName: elastic-es-http-certs-public
