apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: logging
spec:
  version: 8.17.3
  http:
    tls:
      selfSignedCertificate:
        disabled: false  # Включаем HTTPS с самоподписанным сертификатом
  nodeSets:
    - name: default
      count: 1
      config:
        action.auto_create_index: ".*"  # Разрешаем создание всех индексов, включая системные
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
