apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.io/library/logstash:8.5.1
          ports:
            - containerPort: 5044    # Beats input
            - containerPort: 30429   # TCP input
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-es-credentials
                  key: username
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-es-credentials
                  key: password
          volumeMounts:
            - name: pipeline-config
              mountPath: /usr/share/logstash/pipeline
            # NEW! Примонтируем logstash.yml
            - name: logstash-config-vol
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
      volumes:
        - name: pipeline-config
          configMap:
            name: logstash-pipeline
            items:
              - key: logstash.conf
                path: logstash.conf
        # NEW! Добавляем volume для logstash.yml
        - name: logstash-config-vol
          configMap:
            name: logstash-config  # <-- тот ConfigMap, что вы создали
            items:
              - key: logstash.yml
                path: logstash.yml
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
  namespace: logging
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - name: internal-tcp
      port: 5044
      targetPort: 5044
      protocol: TCP
    - name: external-tcp
      port: 30429
      targetPort: 30429
      protocol: TCP
