apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: logging
data:
  logstash.conf: |-
    input {
      tcp {
        port => 30429
        codec => json_lines  # или другой codec, соответствующий формату логов
      }
    }

    filter {
      if "_jsonparsefailure" in [tags] {
        drop { }
      }
    }    

    output {
      elasticsearch {
        hosts => ["https://elastic-es-http.logging.svc.cluster.local:9200"]
        index => "spring-logs-%{+YYYY.MM.dd}"
        
        user => "${ES_USERNAME}"
        password => "${ES_PASSWORD}"
        
        ssl => true
        ssl_certificate_verification => false
      }
   }