apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: logging
data:
  logstash.conf: |-
    input {
      # Внешний порт для доступа извне кластера
      tcp {
        port => 30429
        codec => json_lines
      }

      # Внутренний порт для подключения внутри кластера
      tcp {
        port => 5044
        codec => json_lines
      }
    }

    filter {
      if "_jsonparsefailure" in [tags] {
        drop { }
      }
    }

    output {
      elasticsearch {
        hosts => ["https://elastic-es-http.logging.svc.cluster.local:9200"]
        index => "spring-logs-%{+YYYY.MM.dd}"

        user => "${ES_USERNAME}"
        password => "${ES_PASSWORD}"

        ssl => true
        ssl_certificate_verification => false
      }
    }