apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: logging
  labels:
    app: filebeat
    component: logging
  annotations:
    description: "Filebeat DaemonSet for collecting logs in the Kubernetes cluster"
spec:
  type: filebeat
  version: 8.14.0
  elasticsearchRef:
    name: elastic
  config:
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.pod.name}_${data.kubernetes.namespace}*.log
            json.keys_under_root: true
            json.add_error_key: true

    processors:
      - add_host_metadata: {}
      - add_cloud_metadata: {}
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
          ignore_missing: true

  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat-sa
        securityContext:
          runAsUser: 0
          runAsGroup: 1000
          fsGroup: 1000

        volumes:
          - name: varlogcontainers
            hostPath: