#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: authservice
#  labels:
#    app: authservice
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: authservice
#  template:
#    metadata:
#      labels:
#        app: authservice
#    spec:
#      containers:
#        - name: authservice
#          image: maxim58r/authservice:latest
#          ports:
#            - containerPort: 8080
#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: maxim58r/authservice:latest

          # Переменные окружения
          env:
            - name: LIVENESS_PATH
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LIVENESS_PATH
            - name: READINESS_PATH
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: READINESS_PATH
            - name: LIVENESS_INITIAL_DELAY_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LIVENESS_INITIAL_DELAY_SECONDS
            - name: LIVENESS_PERIOD_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LIVENESS_PERIOD_SECONDS
            - name: READINESS_INITIAL_DELAY_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: READINESS_INITIAL_DELAY_SECONDS
            - name: READINESS_PERIOD_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: READINESS_PERIOD_SECONDS

          # Liveness Probe
          livenessProbe:
            httpGet:
              path: $(LIVENESS_PATH)
              port: 8080
            initialDelaySeconds: $(LIVENESS_INITIAL_DELAY_SECONDS)
            periodSeconds: $(LIVENESS_PERIOD_SECONDS)

          # Readiness Probe
          readinessProbe:
            httpGet:
              path: $(READINESS_PATH)
              port: 8080
            initialDelaySeconds: $(READINESS_INITIAL_DELAY_SECONDS)
            periodSeconds: $(READINESS_PERIOD_SECONDS)


