apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-shared
  namespace: postgres
spec:
  teamId: "chatter"
  volume:
    size: 2Gi
  numberOfInstances: 1
  users:
    postgres:
      - superuser
      - createdb
  databases:
    postgres_shared: postgres
  postgresql:
    version: "15"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
