apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    server:
      port: {{ .Values.server.port | quote }}

    spring:
      application:
        name: {{ .Values.spring.application.name | quote }}

      datasource:
        url: ${IFT_DATASOURCE_URL}
        username: ${IFT_DATASOURCE_USERNAME}
        password: ${IFT_DATASOURCE_PASSWORD}

      liquibase:
        enabled: {{ .Values.spring.liquibase.enabled | quote }}
        change-log: {{ .Values.spring.liquibase.changeLog | quote }}

      jpa:
        hibernate:
          ddl-auto: {{ .Values.spring.jpa.hibernate.ddlAuto | quote }}
        show-sql: {{ .Values.spring.jpa.showSql | quote }}
        properties:
          hibernate.dialect: {{ .Values.spring.jpa.properties.hibernateDialect | quote }}

      elasticsearch:
        uris: ${ELASTICSEARCH_URI}
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}

      security:
        user:
          name: {{ .Values.spring.security.user.name | quote }}

    redis:
      host: ${IFT_REDIS_HOST}
      port: ${IFT_REDIS_PORT}
      connect-timeout: {{ .Values.redis.connectTimeout | quote }}
      password: ${IFT_REDIS_PASSWORD}

    jwt:
      secret: {{ .Values.jwt.secret | quote }}
      expiration: {{ .Values.jwt.expiration | int }}

    logging:
      level:
        org.springframework.boot.context.properties: {{ .Values.logging.level.org.springframework.boot.context.properties | quote }}
        org.hibernate.SQL: {{ .Values.logging.level.org.hibernate.SQL | quote }}
        org.hibernate.type.descriptor.sql.BasicBinder: {{ .Values.logging.level.org.hibernate.type.descriptor.sql.BasicBinder | quote }}

    management:
      endpoint:
        health:
          probes:
            enabled: true
      endpoints:
        web:
          exposure:
            include: health, info, prometheus
      prometheus:
        metrics:
          export:
            enabled: true