apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    server:
      port: {{ .Values.server.port }}

    spring:
      application:
        name: {{ .Values.spring.application.name }}

      datasource:
        url: {{ .Values.spring.datasource.url }}
        username: {{ .Values.spring.datasource.username }}
        password: {{ .Values.spring.datasource.password | default (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name)).data.datasource-password | b64dec }}
      liquibase:
        enabled: {{ .Values.spring.liquibase.enabled | quote }}
        change-log: {{ .Values.spring.liquibase.changeLog | quote }}
      jpa:
        hibernate:
          ddl-auto: {{ .Values.spring.jpa.hibernate.ddlAuto | quote }}
        show-sql: {{ .Values.spring.jpa.showSql | quote }}
        properties:
          hibernate.dialect: {{ .Values.spring.jpa.properties.hibernateDialect | quote }}

      security:
        user:
          name: {{ .Values.spring.security.user.name | quote }}

    redis:
      host: {{ .Values.redis.host | quote }}
      port: {{ .Values.redis.port }}
      connect-timeout: {{ .Values.redis.connectTimeout }}
      password: |
       {{- with (lookup "v1" "Secret" .Release.Namespace "redis-secret") -}}
       {{- if .data.redis-password -}}
       {{ .data.redis-password | b64dec }}
       {{- else -}}
            "default-password"
       {{- end -}}
       {{- end }}

    jwt:
      secret: {{ .Values.jwt.secret | quote }}
      expiration: {{ .Values.jwt.expiration }}

    logging:
      level:
        org.springframework.boot.context.properties: {{ .Values.logging.level.org.springframework.boot.context.properties | quote }}
        org.hibernate.SQL: {{ .Values.logging.level.org.hibernate.SQL | quote }}
        org.hibernate.type.descriptor.sql.BasicBinder: {{ .Values.logging.level.org.hibernate.type.descriptor.sql.BasicBinder | quote }}
