apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "authservice" }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.name | default "authservice" }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name | default "authservice" }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | default "authservice" }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.name | default "authservice" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: app-storage
              mountPath: /data

          # Явное указание переменных через env
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfilesActive }}
            - name: CUSTOM_PORT
              value: "{{ .Values.server.port }}"

          # Подключение глобального ConfigMap
          envFrom:
            - configMapRef:
                name: {{ .Values.globalConfigMap }}

          # Liveness Probe
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.liveness.port }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}

          # Readiness Probe
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: {{ .Values.readiness.port }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc