apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  datasourcePassword: {{ .Values.secrets.datasourcePassword | b64enc | quote }}
  redisPassword: {{ .Values.secrets.redisPassword | b64enc | quote }}
