apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  datasourcePassword: {{ "postgres" | b64enc }}
  redisPassword: {{ "CfAb11y5gLQ3quvc" | b64enc }}
