apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redis-password: {{ "CfAb11y5gLQ3quvc" | b64enc }} # Base64-кодирование
  datasource-password: {{ "postgres" | b64enc }} # Base64-кодирование
