apiVersion: v1
kind: ConfigMap
metadata:
  name: global-configmap
  namespace: default
data:
  LIVENESS_PATH: "/actuator/health/liveness"
  READINESS_PATH: "/actuator/health/readiness"
  LIVENESS_INITIAL_DELAY_SECONDS: "10"
  LIVENESS_PERIOD_SECONDS: "5"
  READINESS_INITIAL_DELAY_SECONDS: "10"
  READINESS_PERIOD_SECONDS: "5"
