extraInitContainers:
  - name: inject-keystore-secret
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    command:
      - sh
      - -c
      - |
        # Создание keystore, если он еще не существует
        if [ ! -f /usr/share/elasticsearch/config/elasticsearch.keystore ]; then
          /usr/share/elasticsearch/bin/elasticsearch-keystore create
        fi
        echo "$CLIENT_SECRET" | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.authc.realms.oidc.oidc1.rp.client_secret -x
    env:
      - name: CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oidc-client-secret
            key: client-secret
    volumeMounts:
      - name: keystore-volume
        mountPath: /usr/share/elasticsearch/config/

volumes:
  - name: keystore-volume
    emptyDir: {}

keystore:
  - secretName: oidc-client-secret  # Имя секрета
    items:
      - key: client-secret  # Ключ внутри секрета
        path: xpack.security.authc.realms.oidc.oidc1.rp.client_secret  # Путь в keystore

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.authc.token.enabled: true
    xpack.security.authc.realms:
      oidc:
        oidc1:
          order: 0
          rp.client_id: "myKeycloakClientId"
          rp.response_type: "code"
          rp.redirect_uri: "http://192.168.1.35:31864/api/security/v1/oidc"
          rp.post_logout_redirect_uri: "http://192.168.1.35:31864/"
          op.issuer: "http://192.168.1.35:32080/realms/Chatter"
          op.authorization_endpoint: "http://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/auth"
          op.token_endpoint: "http://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/token"
          op.jwkset_path: "http://192.168.1.35:32080/realms/Chatter/protocol/openid-connect/certs"
          claims.principal: "sub"
          claims.groups: groups
