apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: chatter-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.210   # пул IP-адресов, которые MetalLB может выдавать
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: chatter-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - chatter-pool
