name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests
        run: |
          echo "Running Tests..."
          mvn test || { echo "Tests failed!"; exit 1; }

      - name: Build Docker Images
        run: |
          for service in auth-service messaging-service chat-service notification-service; do
            echo "Building Docker image for $service..."
            docker build -t maxim58r/$service:${{ github.sha }} ./services/$service
            docker tag maxim58r/$service:${{ github.sha }} maxim58r/$service:latest
          done

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Images
        run: |
          for service in auth-service messaging-service chat-service notification-service; do
            echo "Pushing Docker image for $service..."
            docker push maxim58r/$service:${{ github.sha }}
            docker push maxim58r/$service:latest
          done

      - name: Verify k8s Manifests
        run: |
          if [ ! -d "k8s" ]; then
            echo "k8s directory not found!"
            exit 1
          fi

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Verify Rollout Status
        run: |
          kubectl rollout status deployment/auth-service
          kubectl rollout status deployment/chat-service
          kubectl rollout status deployment/messaging-service
          kubectl rollout status deployment/notification-service

      - name: Health Check
        run: |
          curl --fail http://your-service-url/actuator/health || exit 1

