name: Code Linting and Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven Dependencies
        run: mvn dependency:go-offline

      - name: Run Checkstyle
        run: |
          echo "Running Checkstyle..."
          mvn checkstyle:check

      - name: Run SpotBugs
        run: |
          echo "Running SpotBugs..."
          mvn spotbugs:check

      - name: Lint Summary
        if: failure()
        run: echo "Linting or Static Analysis failed. Please check the logs."

      - name: Upload Checkstyle Report (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

      - name: Upload SpotBugs Report (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml
